---
spring:
  application.name: "PGMan"
  task.scheduling.pool.size: 4

pgman:
  dataSource:
    url: "jdbc:postgresql://172.17.0.130:5432/udtp_inovapar"
    username: "udtp_inovapar"
    password: "udtp_in0v@pAr"
  elasticsearch:
    host: "127.0.0.1"
    port: 9200
    username: "elastic"
    password: "changeme"
    protocol: "http"