---
spring:
  application.name: "PGMan"
  task.scheduling.pool.size: 4

pgman:
  dataSource:
    url: "jdbc:postgresql://172.17.42.1:5432/kasten"
    username: "kasten"
    password: "kasten"
  elasticsearch:
    host: "127.0.0.1"
    port: 9200
    username: "elastic"
    password: "changeme"
    protocol: "http"