version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.13.3
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
    networks:
      - elk

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: 7.13.3
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  pgman:
    image: nexus3.touchtec.com.br:5001/pgman:1.1.0
    environment:
      PGMAN_DATA_SOURCE_URL: "jdbc:postgresql://172.17.42.1:5432/udtp"
      PGMAN_DATA_SOURCE_USERNAME: "postgres"
      PGMAN_DATA_SOURCE_PASSWORD: "postgres"
      PGMAN_ELASTICSEARCH_HOST: "elasticsearch"
      PGMAN_ELASTICSEARCH_USERNAME: "elastic"
      PGMAN_ELASTICSEARCH_PASSWORD: "changeme"
      discovery.type: single-node
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
