version: '3.2'

services:
  elasticsearch:
    container_name: pgman_elasticksearch
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.13.4
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: pgman_elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
    networks:
      - pgman

  kibana:
    container_name: pgman_kibana
    build:
      context: kibana/
      args:
        ELK_VERSION: 7.13.4
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - pgman
    depends_on:
      - elasticsearch

  pgman:
    container_name: pgman
    image: nexus3.touchtec.com.br:5001/pgman
    environment:
      PGMAN_DATA_SOURCE_URL: "jdbc:postgresql://172.17.42.1:5432/postgres"
      PGMAN_DATA_SOURCE_USERNAME: "postgres"
      PGMAN_DATA_SOURCE_PASSWORD: "postgres"
      PGMAN_ELASTICSEARCH_HOST: "pgman_elasticksearch"
      PGMAN_ELASTICSEARCH_USERNAME: "elastic"
      PGMAN_ELASTICSEARCH_PASSWORD: "changeme"
      discovery.type: single-node
    networks:
      - pgman
    depends_on:
      - elasticsearch
      - kibana

networks:
  pgman:
    driver: bridge

volumes:
  pgman_elasticsearch:
