---
spring:
  application.name: "PGMan"
  task.scheduling.pool.size: 4

pgman:
  dataSource:
    url: "jdbc:postgresql://127.0.0.1:5432/postgres"
    username: "postgres"
    password: "postgres"
  elasticsearch:
    host: "127.0.0.1"
    port: 9200
    username: "elastic"
    password: "changeme"
    protocol: "http"