
  
# This is a basic workflow to help you get started with Actions

name: "Build PGMAN Docker images."

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run build script
        run: ./build.sh

      - name: Run build script (push)
        run: ./build.sh push
